In [10]:
import pandas as pd;
import openpyxl;

path = r"H:\Escola\Python\Etapa-3\Atividade_4\CD2022_Populacao_2010_Compatibilizada_20231222.xlsx"
indicador_1 = pd.read_excel(path, header = 2)

In [11]:
indicador_1

,Unnamed: 0,UF,COD. UF,COD. MUNIC,NOME DO MUNICÍPIO,População Município 2010\n(Sinopse),População 2010 (Alterações de Limites até 2022)1,População Censo 2022
0,NaN,RO,11.0,15.0,Alta Floresta D'Oeste,24392.0,24392.0,21494.0
1,NaN,RO,11.0,23.0,Ariquemes,90353.0,90353.0,96833.0
2,NaN,RO,11.0,31.0,Cabixi,6313.0,6313.0,5351.0
3,NaN,RO,11.0,49.0,Cacoal,78574.0,78574.0,86887.0
4,NaN,RO,11.0,56.0,Cerejeiras,17029.0,17029.0,15890.0
...,...,...,...,...,...,...,...,...
5569,NaN,DF,53.0,108.0,Brasília,2570160.0,2572159.0,2817381.0
5570,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5571,NaN,Nota: Para o cálculo das taxas de crescimento ...,NaN,NaN,NaN,NaN,NaN,NaN
5572,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5573,NaN,Fonte: IBGE. Diretoria de Pesquisas - DPE - C...,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
tabela_1 = indicador_1.iloc[0:5570, 1:]

In [13]:
tabela_1

,UF,COD. UF,COD. MUNIC,NOME DO MUNICÍPIO,População Município 2010\n(Sinopse),População 2010 (Alterações de Limites até 2022)1,População Censo 2022
0,RO,11.0,15.0,Alta Floresta D'Oeste,24392.0,24392.0,21494.0
1,RO,11.0,23.0,Ariquemes,90353.0,90353.0,96833.0
2,RO,11.0,31.0,Cabixi,6313.0,6313.0,5351.0
3,RO,11.0,49.0,Cacoal,78574.0,78574.0,86887.0
4,RO,11.0,56.0,Cerejeiras,17029.0,17029.0,15890.0
...,...,...,...,...,...,...,...
5565,GO,52.0,22005.0,Vianópolis,12548.0,12548.0,14956.0
5566,GO,52.0,22054.0,Vicentinópolis,7371.0,7373.0,8768.0
5567,GO,52.0,22203.0,Vila Boa,4735.0,4735.0,4215.0
5568,GO,52.0,22302.0,Vila Propício,5145.0,5145.0,5815.0
5569,DF,53.0,108.0,Brasília,2570160.0,2572159.0,2817381.0

In [14]:
tabela_1.columns

Index(['UF', 'COD. UF', 'COD. MUNIC', 'NOME DO MUNICÍPIO',
       'População Município 2010\n(Sinopse)',
       'População 2010 (Alterações de Limites até 2022)1',
       'População Censo 2022'],
      dtype='str')

In [15]:
tabela_1["diferença"] = tabela_1['População Município 2010\n(Sinopse)'] - tabela_1['População Censo 2022']

In [16]:
tabela_1.to_csv(r"H:\Escola\Python\Etapa-3\Atividade_4\diferença20222010.csv", sep=";")

In [17]:
tabela_result=(
    tabela_1.groupby("UF")[['População Município 2010\n(Sinopse)', "População Censo 2022", "diferença"]]
    .sum()
    .reset_index()
)

In [18]:
tabela_1.to_csv(r"H:\Escola\Python\Etapa-3\Atividade_4\diferença20222010estado.csv", sep=";")